name: 'Check Linear History'
description: 'Verifies that the PR maintains linear history'

runs:
  using: 'composite'
  steps:
    - name: Ensure branch contains latest main commit
      shell: bash
      run: |
        set -euo pipefail

        git fetch origin main

        if [ "$(git rev-parse --is-shallow-repository 2>/dev/null || true)" = "true" ]; then
          git fetch --unshallow || true
        fi

        LATEST_MAIN=$(git rev-parse origin/main)

        if ! git merge-base --is-ancestor "$LATEST_MAIN" HEAD; then
          echo "::error:: Branch is missing the latest main commit ($LATEST_MAIN). Rebase or merge main."
          exit 1
        fi

        echo "[INFO] Branch already contains the latest main commit ($LATEST_MAIN)."